var data = {
	"A":[
      {
      	 id:1,
      	 brand:"阿斯顿·马丁",
      	 types:[
            {
            	name:"V12 Vantage",
            	value:"1"
            },
            {
            	name:"阿斯顿·马丁DB9",
            	value:"2"
            },
            {
            	name:"拉共达Taraf",
            	value:"3"
            },
            {
            	name:"阿斯顿·马丁DB11",
            	value:"4"
            }
      	 ]
      },
      {
      	 id:2,
      	 brand:"奥迪",
      	 types:[
            {
            	name:"奥迪A4L",
            	value:"1"
            },
            {
            	name:"奥迪A6L",
            	value:"2"
            },
            {
            	name:"奥迪Q5",
            	value:"3"
            },
            {
            	name:"奥迪Q3",
            	value:"4"
            },
            {
            	name:"奥迪A3",
            	value:"5"
            }
      	 ]
      } 
	],
	"B":[
      {
      	 id:3,
      	 brand:"宝马",
      	 types:[
            {
            	name:"宝马3系",
            	value:"1"
            },
            {
            	name:"宝马5系",
            	value:"2"
            },
            {
            	name:"宝马X1",
            	value:"3"
            },
            {
            	name:"宝马2系旅行车",
            	value:"4"
            },
            {
            	name:"宝马M5",
            	value:"4"
            },
            {
            	name:"宝马M6",
            	value:"5"
            }
      	 ]
      },
      {
      	 id:4,
      	 brand:"奔驰",
      	 types:[
            {
            	name:"奔驰A级",
            	value:"1"
            },
            {
            	name:"奔驰B级",
            	value:"2"
            },
            {
            	name:"奔驰CLS",
            	value:"3"
            },
            {
            	name:"奔驰JL",
            	value:"4"
            },
            {
            	name:"奔驰SLC",
            	value:"5"
            }
      	 ]
      },
      {
      	 id:5,
      	 brand:"本田",
      	 types:[
            {
            	name:"本田CRV",
            	value:"1"
            },
            {
            	name:"思域",
            	value:"2"
            },
            {
            	name:"广州本田",
            	value:"3"
            },
            {
            	name:"飞度",
            	value:"4"
            },
            {
            	name:"雅阁",
            	value:"5"
            }
      	 ]
      } 
	]
}